(setq my-fcolor "SeaGreen")
(setq my-bcolor "grey10")
;; (setq my-font "-rfx-fixed-medium-r-*-*-*-140-*-*-*-*-*-*")
;; (setq my-bfont "-rfx-fixed-bold-r-*-*-*-140-*-*-*-*-*-*")
;; (setq my-ifont "-rfx-fixed-medium-*-*-*-*-140-*-*-*-*-*-*")
;; (setq my-bifont "-rfx-fixed-bold-*-*-*-*-140-*-*-*-*-*-*")
(add-to-list 'default-frame-alist `(background-color . ,my-bcolor))
(add-to-list 'default-frame-alist `(foreground-color . ,my-fcolor))
(add-to-list 'default-frame-alist `(cursor-color . "red"))
(setq initial-frame-alist default-frame-alist)
(setq special-display-frame-alist default-frame-alist) 
(set-foreground-color my-fcolor)
(set-background-color my-bcolor)
(set-cursor-color "red")
(highlight-current-line-set-bg-color "Black")

(cond ((eq window-system 'x)
       (set-face-foreground 'mode-line "grey")
       (set-face-background 'mode-line my-bcolor)
       (set-face-foreground 'menu "grey")
       (set-face-background 'menu my-bcolor)
       (set-face-background 'show-paren-match "MidnightBlue")
       (set-face-background 'scroll-bar my-bcolor)
       (set-frame-font "Monospace 11")
       ;; (set-default-font my-font)
       ;; (set-face-font 'default my-font)
       ;; (set-face-font 'bold my-bfont)
       ;; (set-face-font 'italic my-ifont)
       ;; (set-face-font 'bold-italic my-bifont)
       )
      (t t))

(defun shisha/client-start-hook ()
  (cond ((eq window-system 'x)
	 (set-frame-font "Monospace 11")
	 )
	(t t))
)
